### ISSUE TITLE
Update Python packaging approach to `pyproject.toml`

### ISSUE THREAD

**Issue by jenstroeger** [googleapis/python-api-common-protos#136] opened 2022-09-05 03:47 UTC
**Is your feature request related to a problem? Please describe.**

After looking through [.circleci/packaging/python](https://github.com/googleapis/api-common-protos/tree/main/.circleci/packaging/python), it seems to me that the Python package uses the somewhat dated `setup.py` approach. There’s much [discussion](https://discuss.python.org/t/removing-setup-cfg-and-setup-py-from-the-packaging-tutorial/16096/102) to remove it from the documentation and to guide packages in migrating to `myproject.toml` ([PEP 631](https://peps.python.org/pep-0631/)). (Also note that according to [this announcement](https://discuss.python.org/t/setup-py-removal-python-3-12/17335) the support for `setup.py` will be removed from Python 3.12 internal packages.)

**Describe the solution you'd like**

It shouldn’t be too difficult to migrate and to follow [the updated packaging guidelines](https://packaging.python.org/en/latest/tutorials/packaging-projects/), and move the package forward to the new approach.

**Describe alternatives you've considered**

Nope.

**Additional context**

Looking at the [current `setup.py`](https://github.com/googleapis/api-common-protos/blob/main/.circleci/packaging/python/setup.py) I don’t see a minimum Python version specified although the classifiers indicate that support for Python 2.7 is required (the classifiers are incomplete too). However, there’s a second repository [googleapis/python-api-common-protos](https://github.com/googleapis/python-api-common-protos/blob/main/setup.py) whose content is generated from _this_ repository? There too, `setup.py` should be replaced.

I’m not sure which one of the repositories is the base…

**Comment by Lawouach** [comment] 2023-01-09 06:52
Hi,

This is indeed a bit of an issue that this lib isn't modernized to match where the Python Packaging ecosystem is going. It does leave warnings when deployed with tools such as PDM.

**Comment by chalmerlowe** [comment] 2023-04-14 19:35
I don't know if it is still a concern, but at one point even if you switched to `pyproject.toml` there was a requirement to provide a shim in `setup.py` if you wanted to be able to install a package in editable mode (i.e. using `pip install -e`):

```
#!/usr/bin/env python

import setuptools

if __name__ == "__main__":
    setuptools.setup()
```

**Comment by jenstroeger** [comment] 2023-07-10 10:42
@chalmerlowe that shouldn’t be an issue anymore, see [here](https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/#editable-installation).

**Comment by parthea** [comment] 2024-12-16 16:02
This feature is still in the backlog. We are preparing to migrate the code in this repository to [google-cloud-python](https://github.com/googleapis/google-cloud-python). I'm going to close this as a duplicate of https://github.com/googleapis/google-cloud-python/issues/13171 which is to track the upgrade for the entire repository.

**Closed by parthea** 2024-12-16 16:02 UTC
Labels: type: feature request, priority: p3
