### ISSUE TITLE
Update Python packaging approach to `pyproject.toml`

### ISSUE THREAD

**Issue by jenstroeger** [googleapis/python-api-common-protos#133] opened 2022-09-06 01:14 UTC
I wanted to replicate issue https://github.com/googleapis/python-api-common-protos/issues/136 here, because it looks like this repo is the correct place for it (in which case feel free to [transfer it](https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository)).

**Comment by parthea** [comment] 2022-09-15 15:39
Thanks for opening this feature request. I'm going to close this as a duplicate of https://github.com/googleapis/python-api-common-protos/issues/136

**Closed by parthea** 2022-09-15 15:39 UTC
