### ISSUE TITLE
Protobuf 4.21.5 breaks google-api-core 2.8.2 for Python 3.8.10

### ISSUE THREAD

**Issue by jtressle** [googleapis/python-api-common-protos#128] opened 2022-08-23 19:30 UTC
Hi,

I upgraded to 2.8.2 and I'm now getting the following error:

I'm getting the following error:
```
  File "/opt/conda/lib/python3.8/site-packages/snakemake/__init__.py", line 619, in snakemake
    workflow.include(
  File "/opt/conda/lib/python3.8/site-packages/snakemake/workflow.py", line 1178, in include
    snakefile = infer_source_file(snakefile, basedir)
  File "/opt/conda/lib/python3.8/site-packages/snakemake/sourcecache.py", line 299, in infer_source_file
    if is_local_file(path_or_uri):
  File "/opt/conda/lib/python3.8/site-packages/snakemake/common/__init__.py", line 67, in is_local_file
    return parse_uri(path_or_uri).scheme == "file"
  File "/opt/conda/lib/python3.8/site-packages/snakemake/common/__init__.py", line 71, in parse_uri
    from smart_open import parse_uri
  File "/opt/conda/lib/python3.8/site-packages/smart_open/__init__.py", line 34, in <module>
    from .smart_open_lib import open, parse_uri, smart_open, register_compressor  # noqa: E402
  File "/opt/conda/lib/python3.8/site-packages/smart_open/smart_open_lib.py", line 35, in <module>
    from smart_open import doctools
  File "/opt/conda/lib/python3.8/site-packages/smart_open/doctools.py", line 21, in <module>
    from . import transport
  File "/opt/conda/lib/python3.8/site-packages/smart_open/transport.py", line 98, in <module>
    register_transport('smart_open.gcs')
  File "/opt/conda/lib/python3.8/site-packages/smart_open/transport.py", line 49, in register_transport
    submodule = importlib.import_module(submodule)
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/conda/lib/python3.8/site-packages/smart_open/gcs.py", line 15, in <module>
    import google.cloud.exceptions
  File "/opt/conda/lib/python3.8/site-packages/google/cloud/exceptions.py", line 24, in <module>
    from google.api_core import exceptions
  File "/opt/conda/lib/python3.8/site-packages/google/api_core/exceptions.py", line 29, in <module>
    from google.rpc import error_details_pb2
  File "/opt/conda/lib/python3.8/site-packages/google/rpc/error_details_pb2.py", line 20, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/opt/conda/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 40, in <module>
    from google.protobuf.internal import api_implementation
  File "/opt/conda/lib/python3.8/site-packages/google/protobuf/internal/api_implementation.py", line 104, in <module>
    from google.protobuf.pyext import _message
TypeError: bases must be types
```

I was able to fix the issue by downgrading my protobuf version to 3.20.1.  

#### Environment details

  - OS type and version: Ubuntu 20.04
  - Python version: 3.8.10
  - pip version: 21.1.2
  - `google-api-core` version: 2.8.2

Thanks

**Comment by parthea** [comment] 2022-09-15 15:41
Hi @jtressle,

I haven't been able to reproduce this issue. I found a similar error and https://github.com/protocolbuffers/protobuf/issues/10012 and [this comment](https://github.com/protocolbuffers/protobuf/issues/10012#issuecomment-1145182703) mentions that the issue could be a bad environment. Please could you try to re-create the issue in a new environment?

**Comment by dhimmel** [comment] 2022-09-29 17:39
I had this error and it was not due to a bad environment... was installing fresh conda envs with additional pip dependencies. Stack trace:

```python-traceback
File ~/miniforge3/envs/tr-dev/lib/python3.9/site-packages/google/protobuf/internal/api_implementation.py:104
    101 if _implementation_type == 'cpp':
    102   try:
    103     # pylint: disable=g-import-not-at-top
--> 104     from google.protobuf.pyext import _message
    105     _c_module = _message
    106     del _message

TypeError: bases must be types
```

Downgrading from protobuf 4.21.6 to 3.18.1 fixed the issue for me.

**Comment by danaradg** [comment] 2022-11-14 15:49
Hey there, 

We're also having issues with the new protobuf version (4.21.3) while using 1.56.4. As far as I understand they implemented a breaking change that requires updates from client libraries.

This is the error we get:
```
...
    from google.cloud import logging as cloud_logging
/usr/local/lib/python3.10/site-packages/google/cloud/logging/__init__.py:18: in <module>
    from google.cloud.logging_v2 import __version__
/usr/local/lib/python3.10/site-packages/google/cloud/logging_v2/__init__.py:25: in <module>
    from google.cloud.logging_v2.client import Client
/usr/local/lib/python3.10/site-packages/google/cloud/logging_v2/client.py:22: in <module>
    from google.cloud.logging_v2 import _gapic
/usr/local/lib/python3.10/site-packages/google/cloud/logging_v2/_gapic.py:18: in <module>
    from google.cloud.logging_v2.services.config_service_v2 import ConfigServiceV2Client
/usr/local/lib/python3.10/site-packages/google/cloud/logging_v2/services/config_service_v2/__init__.py:16: in <module>
    from .client import ConfigServiceV2Client
/usr/local/lib/python3.10/site-packages/google/cloud/logging_v2/services/config_service_v2/client.py:33: in <module>
    from google.cloud.logging_v2.services.config_service_v2 import pagers
/usr/local/lib/python3.10/site-packages/google/cloud/logging_v2/services/config_service_v2/pagers.py:27: in <module>
    from google.cloud.logging_v2.types import logging_config
/usr/local/lib/python3.10/site-packages/google/cloud/logging_v2/types/__init__.py:16: in <module>
    from .log_entry import (
/usr/local/lib/python3.10/site-packages/google/cloud/logging_v2/types/log_entry.py:18: in <module>
    from google.api import monitored_resource_pb2  # type: ignore
/usr/local/lib/python3.10/site-packages/google/api/monitored_resource_pb2.py:30: in <module>
    from google.api import label_pb2 as google_dot_api_dot_label__pb2
/usr/local/lib/python3.10/site-packages/google/api/label_pb2.py:47: in <module>
    _descriptor.EnumValueDescriptor(
/usr/local/lib/python3.10/site-packages/google/protobuf/descriptor.py:755: in __new__
    _message.Message._CheckCalledFromGeneratedFile()
E   TypeError: Descriptors cannot not be created directly.
E   If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
E   If you cannot immediately regenerate your protos, some other possible workarounds are:
E    1. Downgrade the protobuf package to 3.20.x or lower.
E    2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
E   
```

Setting `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python` works, but we'd rather avoid it if possible.
I'm not sure if this package is the problematic one, but the bottom of the stacktrace points to a file in this repo (label_pb2.py).
Assuming the error originates from this repo, is this going to be fixed soon?

**Comment by ohmayr** [comment] 2023-08-14 19:15
Hey @vchudnov-g, I see that you're the last person to interact with this issue, what do you recommend the next steps are?

**Comment by vchudnov-g** [comment] 2023-08-21 22:15
@dhimmel @jtressle @danaradg Are you still seeing this error? Does upgrading to the latest version of the various client libraries you're using help (cf. [this comment](https://github.com/census-instrumentation/opencensus-python/issues/1162#issuecomment-1263651833))?

If this issue is still happening, could you post some reproduction steps (code and dependencies)?

Thanks. We want to get this working for you.

**Comment by parthea** [comment] 2024-04-16 18:05
Closing as obsolete. I believe this was fixed in https://github.com/googleapis/python-api-common-protos/pull/141 and version 1.57.0 or higher. Please open a new issue if you encounter a similar error.

**Closed by parthea** 2024-04-16 18:05 UTC
Labels: needs more info, type: bug, priority: p1
